#### **Pandas DataFrame and Series**

Pandas is a powerful data manipulation library in python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A series is a one-dimensional array-like object, while a data frame is a two dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (row and columns).

In [1]:
import pandas as pd

---
**Series**
  + A pandas series is a one dimensional array-like object that can hold any data type. It is similar to a column in table.

In [9]:
data = list(range(1,6))
print(f"data: {data}")

series = pd.Series(data)
print(f"series:\n{series}")
print(f"type of series: {type(series)}")

data: [1, 2, 3, 4, 5]
series:
0    1
1    2
2    3
3    4
4    5
dtype: int64
type of series: <class 'pandas.Series'>

---
+ series from dictionary elements

In [12]:
data = {
    'a' : 1, 
    'b' : 2,
    'c' : 3,
    'd' : 10
}
dict_series = pd.Series(data)
print(f"series:\n{dict_series}")
print(f"type of series: {type(dict_series)}")

series:
a     1
b     2
c     3
d    10
dtype: int64
type of series: <class 'pandas.Series'>

In [20]:
data = list(range(10,40,10))
index = list(chr(ch) for ch in range(ord('a'),ord('d')))

print(f"index: {index}, data: {data}")

series = pd.Series(data, index=index)
print(series)

index: ['a', 'b', 'c'], data: [10, 20, 30]
a    10
b    20
c    30
dtype: int64

---
**DataFrame**

+ create a data frame from a dictionary of list

In [22]:
data = {
    "Name" : ['siyam','hossain', 'alice'],
    'age' : [21, 23, 25],
    'city' : ['Dhaka', 'Sylhet', 'Comilla']
}
df = pd.DataFrame(data)
print(df)
print("--"*20)
print(type(df))

      Name  age     city
0    siyam   21    Dhaka
1  hossain   23   Sylhet
2    alice   25  Comilla
----------------------------------------
<class 'pandas.DataFrame'>

In [23]:
import numpy as np
np.array(df)

array([['siyam', 21, 'Dhaka'],
       ['hossain', 23, 'Sylhet'],
       ['alice', 25, 'Comilla']], dtype=object)

---
+ create a data frame from a list of dict

In [26]:
data = [
    {
        "Name" : 'siyam',
        "age" : 21,
        "city" : "Dhaka"
    },
    {
        "Name" : 'hossain',
        "age" : 23,
        "city" : "Dhaka"
    },
    {
        "Name" : 'alice',
        "age" : 32,
        "city" : "Dhaka"
    },
    {
        "Name" : 'bob',
        "age" : 35,
        "city" : "Dhaka"
    }
]
df = pd.DataFrame(data)
print(df)
print("--"*20)
print(type(df))

      Name  age   city
0    siyam   21  Dhaka
1  hossain   23  Dhaka
2    alice   32  Dhaka
3      bob   35  Dhaka
----------------------------------------
<class 'pandas.DataFrame'>

---
+ how to read csv file

In [35]:
df_sales = pd.read_csv('002-online-sales-data.csv')

In [36]:
df_sales.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [38]:
df_sales.tail()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

---

In [39]:
data = {
    "Name" : ['siyam','hossain', 'alice'],
    'age' : [21, 23, 25],
    'city' : ['Dhaka', 'Sylhet', 'Comilla']
}
df = pd.DataFrame(data)
df

      Name  age     city
0    siyam   21    Dhaka
1  hossain   23   Sylhet
2    alice   25  Comilla

In [40]:
df['Name']

0      siyam
1    hossain
2      alice
Name: Name, dtype: str

In [41]:
type(df['Name'])

pandas.Series

---
+ for row operation we use loc 
+ .loc = label-based (uses column names + index labels)

In [43]:
df.loc[0]

Name    siyam
age        21
city    Dhaka
Name: 0, dtype: object

In [49]:
# specific value : row + col
df.loc[0,'Name']

'siyam'

In [50]:
# multiple rows and cols
df.loc[0:1, ['Name','city']]

      Name    city
0    siyam   Dhaka
1  hossain  Sylhet

---
+ for col operation we use iloc
+ .iloc = position-based (pure numbers)

In [44]:
df.iloc[0]

Name    siyam
age        21
city    Dhaka
Name: 0, dtype: object

In [51]:
# row 0, col = 1
df.iloc[0, 1]

np.int64(21)

In [52]:
# multiple rows + cols
df.iloc[0:2, 0:2]

      Name  age
0    siyam   21
1  hossain   23

---

In [53]:
data = [
    {
        "Name" : 'siyam',
        "age" : 21,
        "city" : "Dhaka"
    },
    {
        "Name" : 'hossain',
        "age" : 23,
        "city" : "Dhaka"
    },
    {
        "Name" : 'alice',
        "age" : 32,
        "city" : "Dhaka"
    },
    {
        "Name" : 'bob',
        "age" : 35,
        "city" : "Dhaka"
    }
]
df = pd.DataFrame(data)

In [54]:
df.loc[0]

Name    siyam
age        21
city    Dhaka
Name: 0, dtype: object

In [55]:
df.loc[0,'Name']

'siyam'

In [56]:
df.loc[0:2, ['Name','age']]

      Name  age
0    siyam   21
1  hossain   23
2    alice   32

In [58]:
df.iloc[0:2, 0:3]

      Name  age   city
0    siyam   21  Dhaka
1  hossain   23  Dhaka

---
**accessing a specified element**
    
+ using ```at```

In [65]:
df

      Name  age   city
0    siyam   21  Dhaka
1  hossain   23  Dhaka
2    alice   32  Dhaka
3      bob   35  Dhaka

In [66]:
df.at[1,'Name']

'hossain'

In [67]:
# df.at[2:4, ['Name','age','city']] # not possible
df.at[3, 'city']

'Dhaka'

+ using ```iat```

In [68]:
df.iat[2,2]

'Dhaka'

---
+ data manipulation with data frame

In [70]:
df

      Name  age   city
0    siyam   21  Dhaka
1  hossain   23  Dhaka
2    alice   32  Dhaka
3      bob   35  Dhaka

+ add a col

In [77]:
df['salary'] = list(range(50000,90000,10000))
df

      Name  age   city  salary
0    siyam   21  Dhaka   50000
1  hossain   23  Dhaka   60000
2    alice   32  Dhaka   70000
3      bob   35  Dhaka   80000

+ remove a col

In [80]:
# axis = 0 means row
# axis = 1 means col

df.drop('salary',axis=1)

      Name  age   city
0    siyam   21  Dhaka
1  hossain   23  Dhaka
2    alice   32  Dhaka
3      bob   35  Dhaka

In [81]:
df

      Name  age   city  salary
0    siyam   21  Dhaka   50000
1  hossain   23  Dhaka   60000
2    alice   32  Dhaka   70000
3      bob   35  Dhaka   80000

+ to permanently remove

In [82]:
df.drop('salary', axis=1, inplace=True)
df

      Name  age   city
0    siyam   21  Dhaka
1  hossain   23  Dhaka
2    alice   32  Dhaka
3      bob   35  Dhaka

+ want to add existing age col: after 1 year

In [83]:
df['age'] = df['age']+1
df

      Name  age   city
0    siyam   22  Dhaka
1  hossain   24  Dhaka
2    alice   33  Dhaka
3      bob   36  Dhaka

In [84]:
df.drop(0)

      Name  age   city
1  hossain   24  Dhaka
2    alice   33  Dhaka
3      bob   36  Dhaka

In [85]:
df.drop(0)

      Name  age   city
1  hossain   24  Dhaka
2    alice   33  Dhaka
3      bob   36  Dhaka

In [86]:
df

      Name  age   city
0    siyam   22  Dhaka
1  hossain   24  Dhaka
2    alice   33  Dhaka
3      bob   36  Dhaka

In [87]:
df.drop(0, inplace=True)

In [88]:
df

      Name  age   city
1  hossain   24  Dhaka
2    alice   33  Dhaka
3      bob   36  Dhaka

---

In [93]:
df_sales.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [94]:
print(f"Data types: \n{df_sales.dtypes}")

print("--"*25)

print(f"Statistical summary: \n{df_sales.describe()}")

Data types:
Transaction ID        int64
Date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region                  str
Payment Method          str
dtype: object
--------------------------------------------------
Statistical summary:
       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000