#### **Data manipulation and analysis with pandas**

Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform, and extract insights from data. In this lesson, we will cover various data manipulation and analysis techniques using pandas.

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('003-data.csv')

+ fetch the first 5 rows

In [4]:
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

+ last 5 rows

In [5]:
df.tail()

          Date Category  Value   Product  Sales Region
64  2023-03-06        B   14.0  Product2  450.0  South
65  2023-03-07        A   53.0  Product1  610.0   East
66  2023-03-08        C   67.0  Product3  710.0  North
67  2023-03-09        B   81.0  Product2  830.0   West
68  2023-03-10        A   24.0  Product1  920.0  South

+ statistical analysis

In [6]:
df.describe()

           Value         Sales
count  65.000000     66.000000
mean   50.169231    884.787879
std    24.853678   1639.945576
min     7.000000   -120.000000
25%    29.000000    463.250000
50%    49.000000    618.500000
75%    70.000000    811.000000
max    95.000000  10000.000000

+ data types

In [9]:
df.dtypes

Date            str
Category        str
Value       float64
Product         str
Sales       float64
Region          str
dtype: object

---
+ handling missing values

In [10]:
df.isnull()

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
..    ...       ...    ...      ...    ...     ...
64  False     False  False    False  False   False
65  False     False  False    False  False   False
66  False     False  False    False  False   False
67  False     False  False    False  False   False
68  False     False  False    False  False   False

[69 rows x 6 columns]

In [11]:
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
      ...
64    False
65    False
66    False
67    False
68    False
Length: 69, dtype: bool

In [13]:
df.isnull().any()
# True mean missing value present

Date        False
Category     True
Value        True
Product      True
Sales        True
Region       True
dtype: bool

+ sum

In [14]:
df.isnull().sum()

Date        0
Category    1
Value       4
Product     1
Sales       3
Region      1
dtype: int64

---
+ filling missing values with fillna

In [16]:
df_filled = df.fillna(0)
df_filled

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
..         ...      ...    ...       ...    ...    ...
64  2023-03-06        B   14.0  Product2  450.0  South
65  2023-03-07        A   53.0  Product1  610.0   East
66  2023-03-08        C   67.0  Product3  710.0  North
67  2023-03-09        B   81.0  Product2  830.0   West
68  2023-03-10        A   24.0  Product1  920.0  South

[69 rows x 6 columns]

In [17]:
df_filled.isnull().sum()

Date        0
Category    0
Value       0
Product     0
Sales       0
Region      0
dtype: int64